=== uniba-swt/swtbahn-cli/server/doc/api-formats/monitor/json-schema-monitor_route.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "monitor_route.schema.json",
  "title": "route",
  "description": "describes a route. If points and/or conflicting_route_ids fields are missing, likely server-internal err",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "source_signal": {
      "type": "string",
      "minLength": 1
    },
    "destination_signal": {
      "type": "string",
      "minLength": 1
    },
    "orientation": {
      "type": "string",
      "pattern": "^(anticlockwise|clockwise)$"
    },
    "length": {
      "type": "number",
      "$comment": "at least at uni bamberg (swtbahn), these lengths are always in centimeters"
    },
    "path": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": false,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "sections": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "signals": {
      "type": "array",
      "minItems": 2,
      "$comment": "minItems is 2 because at least source and destination signals shall be contained in this array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "points": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "conflicting_route_ids": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "granted_conflicting_route_ids": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "clear": {
      "type": "boolean"
    },
    "granted_to_train": {
      "type": "string",
      "minLength": 0,
      "$comment": "Contains name of the train if the route is currently granted, otherwise empty."
    }
  },
  "required": [
    "id",
    "source_signal",
    "destination_signal",
    "orientation",
    "length",
    "path",
    "sections",
    "signals",
    "points",
    "conflicting_route_ids",
    "granted_conflicting_route_ids",
    "clear",
    "granted_to_train"
  ]
}

=== uniba-swt/swtbahn-cli/api-formats/advanced/monitor_route.json
{
	"id": "54",
	"source_signal": "s1",
	"destination_signal": "s4",
	"orientation": "left", 
	"length": 1213.1,
	"path": ["seg1", "seg2"],
	"sections": ["x1", "x2"],
	"points": ["p1", "p2"],
	"signals": ["s1", "s4"],
	"conflicting_route_ids": ["123","1","2"],
	"granted_conflicting_route_ids": ["1"],
	"clear": false,
	"granted_to_train": ""
}
